### PR TITLE
gem dep consolidation

### PR DESCRIPTION
**Pull request by schwankl**

### CODE REVIEW

**Comment by challsted** [comment]
Pull Request #21 has updated several gems that were not then moved down into `oneops-admin.gemspec`

**Comment by kfilipovski** [comment]
@schwankl the lib/templates/circuit directory is now empty so `circuit create` fails:

~~~ bash
[root@815ef0af0c23 oneops]# circuit create
Could not find "/usr/local/share/gems/gems/oneops-admin-1.0.0/lib/templates/circuit" in any of your source paths. Your current source paths are: 
/usr/local/share/gems/gems/oneops-admin-1.0.0/lib
~~~

**Comment by kfilipovski** [comment]
After manually creating the circuit dir I tested `circuit init` as well as `circuit install` inside circuit-oneops-1 and they both worked fine... so just installing oneops-admin gem without using any other Gemfiles or running bundle installs works fine for running circuit commands.

**Comment by kfilipovski** [comment]
Running `bundle install` inside circuit-oneops-1 now fails due to conflicting dependencies with oneops-admin gem but that should be fixed by removing all gems from that Gemfile and only leaving oneops-admin there and in any other circuit. Also it looks like you will have to remove the bundler gem dependency in the gemspec.

**Comment by kfilipovski** [comment]
Lastly, when using the gem to do `inductor create` it automatically executes the bundle install using the lib/template/inductor/Gemfile.  This doesn't break anything for running future inductor|circuit commands, but we should remove this step when we wrap the local chef-solo with exec-order.

**Comment by schwankl** [comment]
@kfilipovski yes, the inductor will have its side cleaned up too in different pr. The circuit dirs will have their Gemfile w/ oneops-admin dep only.  updated pr w/ circuit/template/readme.md to prevent template dir issue

**Pull request merged**
