### PR TITLE
inductor args ; rm bundle install and Gemfile - use oneops-admin gemspec

### PR DESCRIPTION
**Pull request by schwankl**

### CODE REVIEW

**Comment by challsted** [comment]
Based on the other PR, shouldn't we be upgrading the following gems?  
`gem 'mixlib-shellout', ‘1.6.1’` (from 1.4.0)   
`gem 'mime-types', ‘1.25.1’` (from 1.25)  
`gem 'ohai', ‘7.4.1’` (from 7.4.0)

Im getting multiple errors attempting to deploy, that throw exemptions for the  `mixlib-shellout` gem.

**Comment by kfilipovski** [comment]
@schwankl @challsted I would completely remove those gems from the gemspec... Those are all needed by chef and we can delegate that dependency to whatever that particular version of chef wants/needs.
That said you should not be getting errors during the full build+deploy, but I think there are more changes needed for that:
- re-tag oneops-admin with latest 'stable'
- remove the 'bundle install' lines in circuit and inductor setups in dev-tools scripts

**Comment by schwankl** [comment]
@challsted they are in https://github.com/oneops/oneops-admin/blob/master/oneops-admin.gemspec ... between #23 and #24 and https://github.com/oneops/circuit-oneops-1/pull/85 the gem deps are consolidated into the oneops-admin.gemspec

**Comment by kfilipovski** [comment]
i just merged https://github.com/oneops/circuit-oneops-1/pull/85 so the bundle install should not fail with conflicts now about mixlib-shellout etc... but again, i think everything will need to be re-tagged as stable for the full vagrant install/refresh to work end-to-end.  @schwankl i think we need to add support for the oo-setup.sh script to take tag/ref as argument so we can test everything end-to-end with master before re-tagging it stable... i did something similar here - https://github.com/kfilipovski/setup/blob/master/docker/jenkins/build.sh#L52-L58

**Comment by challsted** [comment]
@kfilipovski im not getting errors on the full build of oneops, i getting errors on deployment of an empty tomcat instance. i assume that is above/beyond testing that is being preformed right now.

**Comment by kfilipovski** [comment]
@challsted yes, the focus is not getting the build+deploy working again including the circuit create/init/install and inductor create/add/start etc.  I think the next step is to update the inductor to invoke exec-order->chef-solo properly using the bundler so it doesn't conflict with the gems specified/needed during the build+deploy.  But you make a good point if we set the correct versions in the gemspec now we can avoid the conflicts even if chef-solo doesn't run in the bundler, so it won't be broken while @schwankl is working on it... Let me complete the test+merge of this PR first to make sure the vagrant install works end-to-end and reproduce your problem on a deployment and then we'll fix that as well.

**Pull request merged**
